"""add is_demo flag to users

Revision ID: fe4a4dd94080
Revises: 80f84d1a1a36
Create Date: 2026-06-23 22:54:32.910607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe4a4dd94080'
down_revision: Union[str, Sequence[str], None] = '80f84d1a1a36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_demo', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_demo')
    # ### end Alembic commands ###
